export const ROUTES = {
  LOGIN: 'Login',
  PHONE_LOGIN: 'PhoneLogin',
  HOME: 'Home',
  WORK_SCHEDULE: 'WorkSchedule',
  MY_WORK_SCHEDULE: 'MyWorkSchedule',
  WORK_SCHEDULE_MENU: 'WorkScheduleMenu',
  WORK_SCHEDULE_LIST: 'WorkScheduleList',
  CREATE_WEEK_SCHEDULE: 'CreateWeekSchedule',
  CHECKIN_CHECKOUT: 'CheckinCheckout',
  MEDICINES_HUB: 'MedicinesHub',
  MEDICINES: 'Medicines',
  EMPLOYEE_MEDICINES: 'EmployeeMedicines',
  MEDICINE_DETAIL: 'MedicineDetail',
  ADD_MEDICINE: 'AddMedicine',
  SUPPLIERS: 'Suppliers',
  ADD_SUPPLIER: 'AddSupplier',

  // Customer routes
  CUSTOMERS: 'Customers',
  CUSTOMER_DETAIL: 'CustomerDetail',
  ADD_CUSTOMER: 'AddCustomer',

  // Warehouse routes
  WAREHOUSE_HUB: 'WarehouseHub',
  IMPORT_LIST: 'ImportList',
  CREATE_IMPORT: 'CreateImport',
  IMPORT_DETAIL: 'ImportDetail',
  INVENTORY_LIST: 'InventoryList',
  INVENTORY_DETAIL: 'InventoryDetail',
  INVENTORY_DETAIL_WITH_BATCHES: 'InventoryDetailWithBatches',
  BATCH_DETAIL: 'BatchDetail',
  BATCH_LIST: 'BatchList',
  BRANCH_INVENTORY_MANAGEMENT: 'BranchInventoryManagement',
  REPORT_SELECTION: 'ReportSelection',
  REPORT_VIEW: 'ReportView',
  // Revenue Report routes
  BRANCH_REVENUE_REPORT: 'BranchRevenueReport',
  BRANCH_EMPLOYEE_LIST: 'BranchEmployeeList',
  BRANCH_EMPLOYEE_INFO_MENU: 'BranchEmployeeInfoMenu',
  BRANCH_EMPLOYEE_SELECTION: 'BranchEmployeeSelection',
  EMPLOYEE_WORK_HISTORY: 'EmployeeWorkHistory',
  EMPLOYEE_WORK_HISTORY_DETAIL: 'EmployeeWorkHistoryDetail',
  BRANCH_WORK_HISTORY: 'BranchWorkHistory',
  ADMIN_WORK_HISTORY: 'AdminWorkHistory',
  EMPLOYEE_REVENUE: 'EmployeeRevenue',
  MEDICINE_MANAGEMENT: 'MedicineManagement',
  // Employee Management routes
  EMPLOYEE_MANAGEMENT: 'EmployeeManagement',
  ADD_EDIT_EMPLOYEE: 'AddEditEmployee',
  // Branch management
  BRANCH_LIST: 'BranchList',
  ADD_EDIT_BRANCH: 'AddEditBranch',
  BRANCH_DETAIL: 'BranchDetail',
  // Sales routes
  SALES: 'Sales',
  CREATE_INVOICE: 'CreateInvoice',
  INVOICE_DETAIL: 'InvoiceDetail',
  INVOICE_LIST: 'InvoiceList',
  BRANCH_INVOICE_HISTORY: 'BranchInvoiceHistory',
  EMPLOYEE_INVOICE_HISTORY: 'EmployeeInvoiceHistory',
  CUSTOMER_LIST: 'CustomerList',
  CUSTOMER_DETAIL: 'CustomerDetail',
  // Categories routes
  CATEGORIES: 'Categories',
  ADD_CATEGORY: 'AddCategory',
  CATEGORY_DETAIL: 'CategoryDetail',
  // Payroll routes
  PAYROLL_MENU: 'PayrollMenu',
  PAYROLL_LIST: 'PayrollList',
  PAYROLL_DETAIL: 'PayrollDetail',
  CREATE_PAYROLL: 'CreatePayroll',
  PAYROLL_SUMMARY: 'PayrollSummary',
  BRANCH_PAYROLL_LIST: 'BranchPayrollList',
  PAYROLL_BRANCH_SELECTION: 'PayrollBranchSelection',
  // Statistics routes
  EMPLOYEE_STATISTICS: 'EmployeeStatistics',
  BRANCH_STATISTICS_HUB: 'BranchStatisticsHub',
  BRANCH_REVENUE_STATS: 'BranchRevenueStats',
  BRANCH_EMPLOYEES_STATS: 'BranchEmployeesStats',
  BRANCH_MEDICINES_STATS: 'BranchMedicinesStats',
  BRANCH_IMPORTS_STATS: 'BranchImportsStats',
  BRANCH_BATCH_STATUS_STATS: 'BranchBatchStatusStats',
  BRANCH_CUSTOMERS_STATS: 'BranchCustomersStats',
  BRANCH_REVENUE_BY_PERIOD_STATS: 'BranchRevenueByPeriodStats',
  // System Admin Statistics routes
  SYSTEM_ADMIN_STATISTICS_MENU: 'SystemAdminStatisticsMenu',
  SYSTEM_ADMIN_BRANCH_LIST: 'SystemAdminBranchList',
  SYSTEM_ADMIN_BRANCH_REVENUE_DETAILED: 'SystemAdminBranchRevenueDetailed',
  SYSTEM_ADMIN_DASHBOARD: 'SystemAdminDashboard',
  SYSTEM_ADMIN_BRANCH_REVENUE: 'SystemAdminBranchRevenue',
  SYSTEM_ADMIN_EMPLOYEE_REVENUE: 'SystemAdminEmployeeRevenue',
  SYSTEM_ADMIN_TOP_MEDICINES: 'SystemAdminTopMedicines',
  SYSTEM_ADMIN_BATCH_STATUS: 'SystemAdminBatchStatus',
  SYSTEM_ADMIN_REVENUE_BY_PERIOD: 'SystemAdminRevenueByPeriod',
  // System Admin Work Schedule routes
  SYSTEM_ADMIN_WORK_SCHEDULE_MENU: 'SystemAdminWorkScheduleMenu',
  SYSTEM_ADMIN_WORK_SCHEDULE_BRANCH_SELECTION:
    'SystemAdminWorkScheduleBranchSelection',
  SYSTEM_ADMIN_WORK_HISTORY_BRANCH_SELECTION:
    'SystemAdminWorkHistoryBranchSelection',
  SYSTEM_ADMIN_BRANCH_WORK_SCHEDULE: 'SystemAdminBranchWorkSchedule',
  SYSTEM_ADMIN_BRANCH_WORK_HISTORY: 'SystemAdminBranchWorkHistory',
} as const;
