export const ROUTES = {
  LOGIN: 'Login',
  PHONE_LOGIN: 'PhoneLogin',
  HOME: 'Home',
  WORK_SCHEDULE: 'WorkSchedule',
  MY_WORK_SCHEDULE: 'MyWorkSchedule',
  WORK_SCHEDULE_MENU: 'WorkScheduleMenu',
  WORK_SCHEDULE_LIST: 'WorkScheduleList',
  CREATE_WEEK_SCHEDULE: 'CreateWeekSchedule',
  CHECKIN_CHECKOUT: 'CheckinCheckout',
  MEDICINES_HUB: 'MedicinesHub',
  MEDICINES: 'Medicines',
  MEDICINE_DETAIL: 'MedicineDetail',
  ADD_MEDICINE: 'AddMedicine',
  SUPPLIERS: 'Suppliers',
  ADD_SUPPLIER: 'AddSupplier',
  // Warehouse routes
  IMPORT_LIST: 'ImportList',
  CREATE_IMPORT: 'CreateImport',
  IMPORT_DETAIL: 'ImportDetail',
  INVENTORY_LIST: 'InventoryList',
  INVENTORY_DETAIL: 'InventoryDetail',
  REPORT_SELECTION: 'ReportSelection',
  REPORT_VIEW: 'ReportView',
  // Revenue Report routes
  BRANCH_REVENUE_REPORT: 'BranchRevenueReport',
  BRANCH_EMPLOYEE_LIST: 'BranchEmployeeList',
  EMPLOYEE_WORK_HISTORY: 'EmployeeWorkHistory',
  EMPLOYEE_REVENUE: 'EmployeeRevenue',
  MEDICINE_MANAGEMENT: 'MedicineManagement',
  // Employee Management routes
  EMPLOYEE_MANAGEMENT: 'EmployeeManagement',
  ADD_EDIT_EMPLOYEE: 'AddEditEmployee',
  // Branch management
  BRANCH_LIST: 'BranchList',
  ADD_EDIT_BRANCH: 'AddEditBranch',
  BRANCH_DETAIL: 'BranchDetail',
  // Sales routes
  SALES: 'Sales',
  CREATE_INVOICE: 'CreateInvoice',
  INVOICE_DETAIL: 'InvoiceDetail',
  INVOICE_LIST: 'InvoiceList',
};
